app:
  test: hi
  scheduler:
    interval: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs

server:
  port: 8181

spring:
  application:
    name: test

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: arina
    driver-class-name: org.postgresql.Driver
    password: "0000"

github:
  token: ${GITHUB_TOKEN}